[toolchain]
anchor_version = "1.2.0"

[features]
resolution = true
skip-lint = false

[programs.localnet]
seal_registry = "SeaLXkRMwaEx7cWWcUtXyTPcbcvRK1Ma3DA3n6nMoEX"

[programs.devnet]
seal_registry = "SeaLXkRMwaEx7cWWcUtXyTPcbcvRK1Ma3DA3n6nMoEX"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[test.validator]
url = "https://api.mainnet-beta.solana.com"

[[test.validator.clone]]
address = "CoREENxT6tW1HoK8ypY1SxRMZTcVPm7R94rH4PZNhX7d"
